# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Grayscale
                                 A QGIS plugin
 Turns rgb rasters into single band rasters.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-25
        copyright            : (C) 2022 by Juho Ervasti
        email                : juho-ervasti@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Grayscale class from file Grayscale.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Grayscale import Grayscale
    return Grayscale(iface)
